# Generated by Django 3.0.3 on 2020-08-12 10:21

from django.db import migrations, models
import location_field.models.plain
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doname', models.CharField(max_length=256)),
                ('doemail', models.EmailField(max_length=256)),
                ('age', models.PositiveIntegerField()),
                ('dophoneno', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('income', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('dchoice', models.CharField(choices=[('1', 'Individual'), ('2', 'Organisation')], default='1', max_length=20)),
                ('estatus', models.CharField(choices=[('1', 'Employed'), ('2', 'Unemployed')], default='1', max_length=20)),
                ('achoice', models.CharField(choices=[('1', 'Individual'), ('2', 'Organisation')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('age', models.PositiveIntegerField()),
                ('phoneno', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('image', models.CharField(default='', max_length=500)),
                ('choice', models.CharField(choices=[('1', 'Individual'), ('2', 'Organisation')], default='1', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
