# Generated by Django 3.0.3 on 2020-08-12 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.PositiveIntegerField()),
                ('item_image', models.CharField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F3%2F34%2FNokia_3310_3G_%252820180116%2529.jpg&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFeature_phone&tbnid=FjmqN9PVVRY7zM&vet=12ahUKEwibhsOs95XrAhV6k0sFHWCbBBEQMygHegUIARDyAQ..i&docid=Jtq_cpENzKzFCM&w=2166&h=2327&q=phone&ved=2ahUKEwibhsOs95XrAhV6k0sFHWCbBBEQMygHegUIARDyAQ', max_length=500)),
                ('item_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=200)),
                ('requirement_quantity', models.PositiveIntegerField()),
                ('requirement_desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='donee',
            name='achoice',
        ),
        migrations.RemoveField(
            model_name='donee',
            name='estatus',
        ),
        migrations.AddField(
            model_name='donee',
            name='affilated_with_NGO',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='donee',
            name='employment_status',
            field=models.CharField(choices=[('1', 'Employed'), ('2', 'Unemployed')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='donee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
